name: "Build Dark Ages kernel on darky."              # Description of the workflow.
on:
  push:
    branches: darky                                   # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build Dark Ages kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
      with:
        repository: SmallPP420/android_kernel_mediatek_mt6761-62-4.9
    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3             # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                   # Specify arch
        compiler: gcc/9                               # Specify toolchain to use
        defconfig: WSP_sprout_defconfig               # Specify defconfig to use
        image: Image.gz-dtb                           # Specify final build file
